version: '2'

services:
  itau-api-todo:
    build:
        context: .
        dockerfile: Dockerfile 
    image: ifood-api-order:1.0
    container_name: ifood-api-order
    hostname: ifood-api-order-docker
    ports:
    - "9090:9090"
    networks:
    - ifood-api-network
networks:
  ifood-api-network:
    driver: bridge